version: '3.8'
services:
  parakeet-api-docker:
    container_name: parakeet-api-docker
    build: 
      context: .
      dockerfile: Dockerfile
      # Enable BuildKit for better build performance and caching
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "5092:5092"
    volumes:
      - ./models:/app/models
      - ./temp_uploads:/app/temp_uploads
    environment:
      # Simplified variables (more options in README.md)
      - MODEL_ID=nvidia/parakeet-tdt-0.6b-v3
      - MODEL_LOCAL_PATH=
      - ENABLE_LAZY_LOAD=true
      - API_KEY=
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]